### ISSUE TITLE
Request is not made if the user change settings before sending it

### ISSUE THREAD

**Issue by rsalas82** [IdeaFlowCo/talktogpt#73]
In web when you launch the request and you have the switches disabled and then before sending the request you enable them, the application does not respond.

https://github.com/IdeaFlowCo/talktogpt/assets/7221710/290cd5e4-d6c2-4cbf-b6f2-f7570586685d

**Comment by rsalas82** [comment]
PR --> #101 
Testing URL --> https://talktogpt-git-fix-cancel-request-change-settings.ideaflow.app

**Comment by sedalar** [comment]
I have to keep testing this error
