### ISSUE TITLE
Race condition error when trying to send two request at the same time (written and spoken)

### ISSUE THREAD

**Issue by rsalas82** [IdeaFlowCo/talktogpt#76]
When you make two requests at the same time, both written and spoken, sometimes the app has problems detecting which request comes in before or after.

https://github.com/IdeaFlowCo/talktogpt/assets/7221710/c2187d5d-95a7-4a40-84be-003cbc7a57e2

**Comment by rsalas82** [comment]
PR --> #100 
Testing URL --> https://talktogpt-git-fix-disable-send-two-requests.ideaflow.app/

**Comment by sedalar** [comment]
This bug has been fixed, delete if you have written something previously to the request or else it doesn't let you send the request until the first one has entered without problem.
Fixed
