### ISSUE TITLE
Delay after the app has recognized the terminator word

### ISSUE THREAD

**Issue by rsalas82** [IdeaFlowCo/talktogpt#80]
There is a delay after saying the terminator word, it appears in the screen and the sound is played.

**Comment by rsalas82** [comment]
We added a "terminator timeout" for this purpose. If the user says "terminator" and wait X seconds (1 by default), the dictation ends, but if the user says "terminator" and continue talking, that word is supposed to be in the request and the request doesn't stopJacob ask us for setting the default value of "Terminator timeout" setting to 0 (zero).
--> https://ideaflowteam.slack.com/archives/C061NKYL0SZ/p1700958114182539?thread_ts=1700730215.297509&cid=C061NKYL0SZ

**Comment by rsalas82** [comment]
Jacob ask us for setting the default value of "Terminator timeout" setting to 0 (zero).
--> https://ideaflowteam.slack.com/archives/C061NKYL0SZ/p1700958114182539?thread_ts=1700730215.297509&cid=C061NKYL0SZ

**Comment by rsalas82** [comment]
PR --> #98 
Testing URL--> https://talktogpt-git-fix-default-terminator-word-timeout-to-zero.ideaflow.app/

**Comment by sedalar** [comment]
The test went well, only once at the beginning I got this error.
![Bug6](https://github.com/IdeaFlowCo/talktogpt/assets/133207203/62b7e6d8-fe33-4af7-84b0-274aed97a431)
But when I tried to provoke it again, it didn't happen any more times.

**Comment by rsalas82** [comment]
It looks like something puntual, let me mark the issue as OK then.
