### ISSUE TITLE
[Android] After a chatGPT error, the next request dictate the error again

### ISSUE THREAD

**Issue by rsalas82** [IdeaFlowCo/talktogpt#87]
When you have a long conversation, I managed to reproduce an error in which the first thing that happens is that you can not connect to the chatgpt that is the first alert and if you make a request saying over captures it but when it will respond the microphone is still listening so the request stops and the microphone button does not work.

https://github.com/IdeaFlowCo/talktogpt/assets/7221710/ca919e19-6547-4ac6-a9a5-be2688496f02

**Comment by sedalar** [comment]
I have not been able to reproduce this error, I have had a 15 minutes conversation with the application and I have not been able to detonate the error, tomorrow I will try again and if I can't detonate it, it is fixed.

**Comment by sedalar** [comment]
It's fixed
