### ISSUE TITLE
Use the same keyword for wake and terminator

### ISSUE THREAD

**Issue by rsalas82** [IdeaFlowCo/talktogpt#92]
Let the user selects the same word for wake and terminator actions.

**Comment by rsalas82** [comment]
There was an error in the blue bubble chat in this case. We were cutting two times the wake-word and, for a while, the blue bubble chat appeared empty.

**Comment by sedalar** [comment]
This case works fine on Web, but on IOS and Android it has more problems, basically the problem is that they have more lag and the communication is not so fluid to detect the terminatorword.
But the error that Rafa comments, has not appeared to me at any time.
